[package]
name = "frost"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"
name = "frost"

[[bin]]
path = "src/bin/main.rs"
name = "demo"
description = "Temporary demo program for development purposes"

[dependencies]
eframe = "0.19.0"
